mongodb:
    image: mongo:8.0
    container_name: ldds-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-ldds}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-lddspass}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-lddsdb}
    command: ["mongod", "--bind_ip_all", "--auth"]
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","bash -c 'echo > /dev/tcp/127.0.0.1/27017'"]
      interval: 5s
      timeout: 3s
      retries: 20
